[project]
name = "perf-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "baml-py==0.56.0",
    "pydantic>=2.9.2",
]
